### ISSUE TITLE
Unable to import iris_grib

### ISSUE THREAD

**Issue by jweisbaum** [SciTools/iris-grib#273]
Environment: Docker running Ubuntu 18.04 with Conda 4.10.1 on Mac 11.4
Conda list tells me I'm running these versions:
iris: 3.0.2
iris-grib: 0.17.0

When I run `>>> import iris_grib` I get this output:
```
>>> import iris_grib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/iris/lib/python3.7/site-packages/iris_grib/__init__.py", line 28, in <module>
    from iris.util import _array_slice_ifempty
ImportError: cannot import name '_array_slice_ifempty' from 'iris.util' (/opt/conda/envs/iris/lib/python3.7/site-packages/iris/util.py)
```
When I try to save a grib with iris, I get this:
```
>>> import iris
>>> ## import a cube ...
>>> iris.save(cube, 'mygrib.grib2')
Traceback (most recent call last):
  File "/opt/conda/envs/iris/lib/python3.7/site-packages/iris/io/__init__.py", line 259, in _grib_save
    from iris_grib import save_grib2
  File "/opt/conda/envs/iris/lib/python3.7/site-packages/iris_grib/__init__.py", line 28, in <module>
    from iris.util import _array_slice_ifempty
ImportError: cannot import name '_array_slice_ifempty' from 'iris.util' (/opt/conda/envs/iris/lib/python3.7/site-packages/iris/util.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python_test.py", line 72, in <module>
    iris.save(cube,'test.grib2')
  File "/opt/conda/envs/iris/lib/python3.7/site-packages/iris/io/__init__.py", line 424, in save
    saver(source, target, **kwargs)
  File "/opt/conda/envs/iris/lib/python3.7/site-packages/iris/io/__init__.py", line 262, in _grib_save
    "Unable to save GRIB file - "
RuntimeError: Unable to save GRIB file - "iris_grib" package is not installed.
```
Thanks.

**Comment by jweisbaum** [comment]
Forgot to add I'm using Python  3.7.10 in my environment. I now see the release 0.17.1 removes something that looks related to my issue. The question is until 0.17.1 is released, what compatible version of iris do I use with 0.17.0? Thanks.

**Comment by lbdreyer** [comment]
@jweisbaum The change that broke iris_grib 0.17.0 was introduced in iris 3.0.2 so if you use iris 3.0.1, it should work.

We are hoping to get the 0.17.1 release out in the next couple of days so hopefully this should be fixed soon!

**Comment by jweisbaum** [comment]
Thanks so much. I've been beating my head against this all weekend. You rock.

**Comment by MHBalsmeier** [comment]
Could you publish 0.17.1 on pypi?
